/* eslint-disable @next/next/no-css-tags */
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <link
        rel='stylesheet'
        href='//cesium.com/downloads/cesiumjs/releases/1.111/Build/Cesium/Widgets/widgets.css'
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
